### ISSUE TITLE
 Server Response Differentiates Between Incorrect Email and Password (Leads to User Enumeration Risk)

### ISSUE THREAD

**Issue by IC3-512** [Letgamer/rsPass#2]
The server currently provides different HTTP status codes and messages for incorrect email and incorrect password scenarios during the login process:

    Incorrect email: Returns 404 with the message:
    "User with that email doesn't exist."
    Incorrect password: Returns 401 with the message:
    "Invalid email or password."

This behavior introduces a user enumeration vulnerability by revealing whether a specific email exists in the system. Attackers can exploit this to determine valid user accounts.
Expected Behavior

The server should return the same generic response for both cases, such as:

    Status Code: 401
    Message: "Invalid email or password."

This prevents attackers from distinguishing between invalid emails and incorrect passwords.
Steps to Reproduce

    Attempt to log in with a non-existent email.
        Observe the 404 status and the message: "User with that email doesn't exist."
    Attempt to log in with an existing email but an incorrect password.
        Observe the 401 status and the message: "Invalid email or password."

Impact

This behavior can lead to:

    User Enumeration Attacks: Attackers can brute-force the system to discover valid email addresses.
    Privacy Concerns: Exposing whether an account exists violates the principle of secure authentication.

Proposed Solution

    Update the server response to use the same status code (401) and message ("Invalid email or password") for all login failures.
    Log detailed error information internally to assist with debugging, while keeping the response to the client generic.

Updated Response Example

For both invalid email and password attempts:

    Status Code: 401
    Message: "Invalid email or password."

Additional Context (For someone that doesn't believe this is an issue @Letgamer ):

This change aligns with authentication best practices by reducing the risk of exposing sensitive account information, CWE-200 (https://cwe.mitre.org/data/definitions/200.html).

**Comment by Letgamer** [comment]
Hi @IC3-512 ,

Thank you for your input. While I understand the concern about user enumeration and privacy, I believe this is not a genuine vulnerability in the context of secure authentication for the following reasons:

### 1. **General Authentication Best Practices**
The proposed behavior to return the same generic error message (401 with "Invalid email or password") for both cases can indeed be part of standard practices. However, it is important to note that many systems use different status codes (404 for email not found, 401 for invalid credentials) to provide more granular error reporting on the server-side, without exposing sensitive data.

### 2. **Access Control and Rate Limiting**
Even if an attacker is able to distinguish between invalid emails and incorrect passwords, it is crucial to implement strong rate-limiting, brute force protection, and account lockouts. These mechanisms are the primary defense against user enumeration attacks, as they prevent repeated attempts on the same account and ensure that enumeration is not easily scalable. 

### 3. **No Sensitive Information is Exposed**
The response indicating "User with that email doesn't exist" could be considered a minor clue. However, attackers would still need access to the login form to attempt enumeration, and the most sensitive data (password hashes) is never exposed. The principle of least privilege is maintained because the server doesn't give access to any account-specific data; it merely confirms the failure of authentication.

---

In conclusion, while the suggestion is a valid best practice, I do not believe this introduces a critical vulnerability in the system, especially if complementary security measures like rate-limiting and account lockout mechanisms are in place. The additional risk posed by this behavior is minimal, and the best mitigation comes from ensuring comprehensive security controls at other layers of the authentication process.

Best regards
